spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

jwt:
  secret:
    key: "YXNkZnF3ZXJ6eGN2MTIzNCEjJFFXRVJBU0RGWlhDVjEyMzQ="

server:
  port: 8080
